### ISSUE TITLE
Intercom adress selection via web interface

### ISSUE THREAD

**Issue by Elektroarzt** [Elektroarzt/simplebus2-mqtt-bridge#2]
At the moment the intercom address has to be entered in secrets.h and will then be hard compiled. A selection via web interface and storage in the ESP32s EEPROM would be useful. 'High end' function would be learning of the address by ringing the bell and reading out the intercom address from the S2 Bus.

**Comment by Gurkenflieger** [comment]
Teach in and manual selection of intercom address added in recent commit
