### ISSUE TITLE
Recognition of entry door ring not working

### ISSUE THREAD

**Issue by alexdetsch** [Elektroarzt/simplebus2-mqtt-bridge#5]
I have the problem that the doorbell at the front door is not recognized. However, ringing the doorbell at the apartment door and opening the front door works without any problems. I have already checked the signals with Elektroarzt and they should actually be correct. The message in the signal from the front door is also correct (my intercom system also rings). Following is a picture of the oscilloscope. 
![DS1Z_QuickPrint38](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/2041432/53070a22-6bba-43ba-b118-5d21f951b6d2)

Yellow is the signal in front of the comparator, blue behind it (at S2). The firmware is from 2024-02-07 15:19. The gain is currently set to 80 (much too high actually, I know), the voltage threshold to 200. I have tried gain in the range of 7-80 and voltage threshold of 100-200, as well as with and without activated "filter"-checkbox.

**Comment by Gurkenflieger** [comment]
This could be a Timing Problem. Habe you tested RingToOpen? Does it work. I can imagine that the mqtt send command is too early and the power is insufficient directly after the ring command.

**Comment by alexdetsch** [comment]
I tried that now, but it didn't work (both with and without attached loudspeaker).
All my other attempts the other days were without the loudspeaker handheld, so I think there wasn't much of a voltage drop while ringing. And I don't think there should be any difference between the front door and the apartment door from the voltage drop regard?

**Comment by Gurkenflieger** [comment]
You can debug the Software with an attached pc in the stdout. There should be debug messages which are commented out. They print the single recognized bits. Is it possible to comment them in ?

**Comment by alexdetsch** [comment]
I can try, but unfortunately I can't find all the dependencies. It would be nice if you could add a few more details about which specific library is meant (GitHub link?). Currently I can't find the debounce library.

**Comment by Gurkenflieger** [comment]
Sry here is the github link of the debounce lib. 
 https://github.com/wkoch/Debounce i'm using v1.2

**Comment by alexdetsch** [comment]
Ok, the address and msgCode is recognized correctly: 
![grafik](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/2041432/216ddcc9-72cc-48f4-bfda-8d47f076fd05)
So it's probably an easy fix :) I'll debug a little bit

**Comment by alexdetsch** [comment]
Yes, I had everything correct.
The bug is in [L464](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/blob/main/software/main.cpp#L464). When messageCode 48 is sent, there is just a break. I removed it and now it works flawlessly. Maybe it worked for you because you have an other Intercom? My entry door intercom send msgCode 48 (as shown in the image above) instead of 50.

**Comment by Gurkenflieger** [comment]
Thanks, of course intercoms without a screen hava an other message.  I will update the code soon. Thanks for the work!

**Comment by Elektroarzt** [comment]
By the way ... what gain and threshold values are working for you after the fix?

**Comment by alexdetsch** [comment]
Currently I still have 80 gain and 150 voltage threshold cause I didn't bothered with them anymore after it worked finally. But initially the two functions ring on apartment door and open entry door worked with the default values.

I already built the module behind my Intercom, so its kinda complex to get it in configuration mode when I'm not wrong (which eliminates the advantage of remote firmware updates for me, because I still need physical access).
Or is there currently a way to activate the configuration mode remotely? I'm thinking about implementing an activate-conf-mode-over-mqtt-feature, what do you think about that?

**Comment by Elektroarzt** [comment]
There is no way for remote activation currently. What do you think of conf-over-MQTT instead of activating the conf mode or both? Of course one has to initially config via Web Interface. But to change some values it could be cool to have all parameters at MQTT-hand.

**Comment by alexdetsch** [comment]
Above I meant to activate the conf mode over MQTT. I also implemented it in my fork already to tinker around (but didn't tested it yet cause of laziness to take the intercom apart again). But you're right, having the config values (gain, threshold, filter) on hand via MQTT is also a very nice idea! (don't know why I didn't think of this very obvious idea 😶‍🌫️)

**Comment by Gurkenflieger** [comment]
Activating the config mode with mqtt is a good idea 👍.

**Comment by richardneitzke** [comment]
> it worked all the way down to gain=1 and threshold=1 and at this point I'm not sure if the values are set correctly (I had 8 tries from gain=80 and threshold=200)

@alexdetsch maybe your settings have no effect at all, that’s what I ran into (#7)

**Comment by Gurkenflieger** [comment]
Maybe the resistors are stuck at a wrong state and the reset does not work as intended. I can add a send command to reset the resistors. Will update the code soon.

**Comment by Gurkenflieger** [comment]
It should work now with 600mV comparator voltage and 20 Gain. Can you test it?
