### ISSUE TITLE
Add setup with MQTT and start webconfig with MQTT 

### ISSUE THREAD

**Issue by Gurkenflieger** [Elektroarzt/simplebus2-mqtt-bridge#6]
-Add setup of filter, gain and comparator voltage with    mqtt.
-Start Webinterface with MQTT.
-Improve MQTT send command.

**Comment by Elektroarzt** [comment]
If you put your hands on the web interface function and can reproduce it, could you have a look at the exit procedure? From time to time I experience the LED not going off after changing parameters and leaving the web interface via save button. I then shortly disconnect bus power to return to normal operation. Could be critical, if the config is started by MQTT and can't be exited remotely.

**Comment by Gurkenflieger** [comment]
Now implemented with improved MQTT commands.
