### ISSUE TITLE
Changing the level/threshold parameters has no effect

### ISSUE THREAD

**Issue by richardneitzke** [Elektroarzt/simplebus2-mqtt-bridge#7]
I'm using a V2.2 bridge provided by @Elektroarzt and so far I haven't managed to make things work. I switched to the latest firmware (3b4bd75) for debugging and noticed that the "level" (`compVoltLvl`) parameter does not seem to have any effect on the comparator reference voltage (D2).

The level parameter appeared to be working with the original firmware that shipped with the bridge. I haven't actually measured it but changing it seemed to have an effect on the detection quality.

I measure an average of about 1.03V on D2, no matter whether the level is set to 150mV (`setPotValue(6)`) or 500mV (`setPotValue(22)`):

![DS1Z_QuickPrint70](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/5ce540c5-c724-4387-ab7d-3200c7b5a0d7)

**Comment by richardneitzke** [comment]
I also checked whether changing the "gain" parameter has any noticeable difference on the comparator input (measured at the "R1-1" pad) and it seems like that isn't the case either. The level of the signal at that pad is about the same when I set gain to 5 vs. 50.

This indicates that this isn't specific to the "level" parameter but rather an issue with the connection to the MCP4017 potentiometer?

**Comment by richardneitzke** [comment]
@Gurkenflieger I only have a very vague idea of what I'm doing but I made some changes and the voltage on D2 is now in the ballpark of what I configure it to. I think this is still not the correct reset sequence (it should have another start bit after the 9 "1" bits).

In `setupI2C(int)`:

```C++
Wire.begin(sdaPin, sclPin, I2C_FREQ);
Wire.beginTransmission(0b111111111);
Wire.endTransmission();
```


At the end of `setPotValue(byte)`:

```C++
Wire.end();
```

**Comment by Gurkenflieger** [comment]
Which version did you use? already implemented an almost similar fix in the recent Version. 
Wire.beginTransmission(0xFF);
 Wire.endTransmission();
 this worked with my stuck Resistor.

**Comment by richardneitzke** [comment]
> Which version did you use? already implemented an almost similar fix in the recent Version.

I referenced the commit in my initial message, seems like it contained the fix you referenced.

> can you test this?

I'll test it later, the code I posted seemed to do the trick so I assume yours will also work 👍

**Comment by Gurkenflieger** [comment]
Wirh the new commit the values will change.
