### ISSUE TITLE
No pulses on S2

### ISSUE THREAD

**Issue by richardneitzke** [Elektroarzt/simplebus2-mqtt-bridge#8]
When I ring the floor door and observe the comparator input ("R1-1") and the payload signal (S2 debug pin) I don't see a clean PWM signal on S2. Right now, the firmware is unable to decode messages from signals like this. I could try to make this work in software but I was hoping that we can find a way to have clean signals for installations like mine.

Here's the full signal, C1 being the payload signal and C2 the comparator input as reference. Notice how the burst is not oscillating cleanly on the comparator input and barely oscillating on S2:

![IMG_0583](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/52a25931-b039-48cb-b283-e29044d5b876)

| Two bursts as an example | Closeup of a single burst |
| -- | -- |
| ![IMG_0585](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/35211aa7-ac27-4f21-b4dd-1f999fb130af) | ![IMG_0584 2](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/649ab5db-a8e3-4648-81de-4cd518d300f0) |

Here is a closeup of the acknowledgement bursts (presumably by the main unit). These are basically perfect. I optimized my gain/threshold values for these pulses (raising them to about 500mV at the comparator input as recommended by @Elektroarzt):

![IMG_0586 2](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/90059aa2-5885-4e9d-a4d9-f0275f9ebae6)

 (Sorry for the photos, my scope stopped accepting USB drives...)

**Comment by Gurkenflieger** [comment]
Have you tried disabling the Filter?

**Comment by richardneitzke** [comment]
> Have you tried disabling the Filter?

No, I haven't tried to bypass the HW filter.

> I uploaded a new version. Can you test this one?

The measurements above were taken on a [modified FW](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/issues/7#issuecomment-1971938850) that was almost identical to the new version (the I2C connection to the MCP4017's seemed to work). I don't think using the new version would make a difference but I can try?

> Does your intercom has a screen?

Yes 👍

> I Also will change the interrupt detection from rising to Falling or Change. This could fix your problem!

Yes, that would work. I was hoping we would find a HW fix which results in a regular signal. Working around the irregular signal in SW is probably less reliable than adjusting the HW so that it either serves clean bursts or no bursts at all on S2?

**Comment by Gurkenflieger** [comment]
Not the hardware filter but the software filter in the webconfig. You can also turn down the Gain. This should help alot!

**Comment by richardneitzke** [comment]
Yes, I turned off the software filter 👍 This issue is mostly about the hardware though, wouldn't it be more desirable to ensure a clean signal as opposed to working around the irregular signal in the firmware?

> You can also turn down the Gain. This should help alot!

There's a fairly big delta in amplitude between the signal from my intercom and the signal from the main unit. I tweaked the gain value so that I can reliably detect signals from the main unit (as seen in the last image of my initial post). If I reduce the gain I would most likely lose the ability to detect these, right?

**Comment by Gurkenflieger** [comment]
Ah you should tweak the gain and comparator voltage not on the acknowledge bursts but on the message itself. The acknowledge is always way higher than the message itself. The software only looks for the message not the acknowledge. Which values did you set for the gain? The could be way too high and induce noise.  Try gain 10 and 200mV. Then you can also use the debut messages and comment thwm in.

**Comment by richardneitzke** [comment]
> Ah you should tweak the gain and comparator voltage not on the acknowledge bursts but on the message itself. [...] The software only looks for the message not the acknowledge. 

I realise that, but the message I measured above comes from my intercom. I would like to be notified of messages from my intercom (in case somebody rings at my apartment door) as well as messages from the main unit (in case somebody rings at the house door downstairs). As you write, there is a big difference in amplitude between the two. Yet, I want to be able to decode both. If I reduce the gain, wouldn't I lose the ability to decode messages from the main unit (which are currently decoded perfectly, see the acknowledgement bursts which come from the main unit in the last image)?.

>  The acknowledge is always way higher than the message itself.

At least in my installation that doesn't seem to be the case when the message comes from the intercom itself. I assume the acknowledgement comes from the main unit (which is why the amplitude is much lower in that case).

> A clean PWM is not necessary. The software measures time between too high signals (in future release between too pin changes). The measured time (pause time) determines if it's a 0 or 1 or a start bit.

Huh, this puzzles me. Could you please elaborate? If I understand the current iteration of the software correctly it _does_ rely on a clean PWM signal. My understanding is that the software would interpret a noisy PWM burst such as the one I posted above ("Closeup of a single burst") as a "0" because the burst itself contains a ~2.5ms "pause" between two rising edges.

There surely are ways to clean up the signal in software but I would only go there if there are no ways to improve the signal quality itself.

**Comment by Gurkenflieger** [comment]
No only if the filter is enabled a more or less clean PWM signal is necessary. Without the software filter it measures the time between two bursts or the time between two high pins. The PWM itself does not matter i just need a high signal.

**Comment by richardneitzke** [comment]
> No only if the filter is enabled a more or less clean PWM signal is necessary. Without the software filter it measures the time between two bursts or the time between two high pins. Its just ja timer that resets if a high signal is detected. If the timer reaches a certain value it determines if its a 0 or 1 or start bit.

This is a 3ms burst, by itself it shouldn't be decoded into a 0/1. My understanding is that the current firmware measures the pauses between rising edges, that's what you describe as well (_"a timer that resets if a high signal is detected"_). This burst has a rising edge at the trigger point and about 2.4ms after the trigger point. Wouldn't the firmware decode this as a 0-bit because the pause is between 2ms...4.9ms?

![IMG_0584 2](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/befc0461-6c75-4797-a4e8-e7ee3a3330eb)

**Comment by richardneitzke** [comment]
Just to reiterate: I realize that this can be fixed in software by introducing stricter timing requirements and also taking falling edges into account. But to me the underlying issue appears to be on the hardware-side and we’d be better off fixing it there instead. It seems like that would result in a more stable system overall.

**Comment by Gurkenflieger** [comment]
Now i see your problem. Where is the Bridge connected? Because your Signal is so high its near the main unit and not the Screen? Try turning down your Gain and turning up your comparator voltage to 600-800mV. I will revisit the problem.

**Comment by richardneitzke** [comment]
I think there’s still a misunderstanding, so I’ll just repeat 😅

I recorded this when my floor door was rung. The message comes from the intercom unit itself. The acknowledgement comes from the main unit.

The messages from the main unit are decoded fine but I also want to decode the messages from my intercom unit. If I reduce the gain and increase the comparator voltage I won’t be able to decode the messages from the main unit anymore.

**Comment by Elektroarzt** [comment]
This is your measuring setup, right?
<img width="1108" alt="image" src="https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/61664171/98b99c47-d0eb-41f6-9fb1-b5ef31eb9c64">

**Comment by Gurkenflieger** [comment]
Now i understand your Problem. I dont know if there is an easy hardware solution for the comparator. Like i said the PWM is not necessary and we can easily find a software fix. We can also bypass the comparator which seems to be too slow and check the raw signal with the esp. Bypassing the comparator is already considered in the current design but we have to write software to check the signal at the analog in.

**Comment by richardneitzke** [comment]
> This is your measuring setup, right?

@Elektroarzt Yes, that's it 👍

> Can you post the signal from the entry door which needs to be amplified? Which gain did you set?

@Gurkenflieger here's what the signal from the entry door looks like (gain = 1, compVoltLvl = 250):

![entry_ring](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/5949796/01631e45-2468-4094-8773-9766d4723227)

**Comment by Gurkenflieger** [comment]
I updated the Code and now my floordoor and on some other intercoms are now working correctly. Can you try it out with the latest firmware. You have to set Gain 20 and 600 mV.

**Comment by Elektroarzt** [comment]
Have you seen the how-to for the tuning process I wrote? See [here](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/blob/7138530772fd946b185f70a6c94b0642a4dc3e89/software/tuning%20process.md).

**Comment by richardneitzke** [comment]
I had a look at the commits that have been made since I raised the issue and maybe I'm missing something but I don't see any changes that address the underlying issue I described [here](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/issues/8#issuecomment-1974823521)? So I don't think tuning the gain/threshold values would do any good here?

**Comment by Elektroarzt** [comment]
The behavior you described is normally caused by too high gain, it's not an issue in the firmware in my opinion. Which gain did you set in the given picture? I can reproduce this beginning from gain around 30. Did you follow the tuning sequence as described?

Gain set to 25:
![image](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/61664171/52fb2cb0-5338-43b8-a720-daa1d57155f3)

Gain set to 30:
![image](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/assets/61664171/ca55270f-463b-4a20-a66f-45c1b1c34662)

**Comment by richardneitzke** [comment]
Ah thank you, that makes sense! I don't recall the gain value I used for the picture but I will try tuning it again 👍

**Comment by Elektroarzt** [comment]
I saw you've set 1 as gain in one post. This was never an allowed value but was not restricted by the legacy firmwares. Be sure to have the newest firmware running before doing the tests, as it checks for the correct range.

**Comment by richardneitzke** [comment]
> I saw you've set 1 as gain in one post. This was never an allowed value but was not restricted by the legacy firmwares. Be sure to have the newest firmware running before doing the tests, as it checks for the correct range.

Thanks for the hint 👍 I assume that most of my settings back then did not actually apply correctly due to the I2C bug. I will try tuning it again on the latest FW.
